apiVersion: v2
appVersion: "v2.8.3"
name: aws-load-balancer-controller-bundle
description: AWS Load Balancer Controller Bundle with Crossplane resources
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
version: ""
kubeVersion: ">=1.17.0-0"
home: https://github.com/giantswarm/aws-load-balancer-controller-app
sources:
  - https://github.com/giantswarm/aws-load-balancer-controller-app
annotations:
  application.giantswarm.io/team: phoenix
