{{- $clusterName := (include "cluster-name" .) -}}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: {{ $clusterName }}-aws-load-balancer-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-load-balancer-controller-bundle.labels" . | nindent 4 }}
spec:
  url: {{ .Values.ociRepositoryUrl }}
  interval: 1h
  ref:
    tag: {{ .Chart.AppVersion }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $clusterName }}-aws-load-balancer-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-load-balancer-controller-bundle.labels" . | nindent 4 }}
spec:
  interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  kubeConfig:
    secretRef:
      name: {{ $clusterName }}-kubeconfig
  chartRef:
    kind: OCIRepository
    name: {{ $clusterName }}-aws-load-balancer-controller
    namespace: {{ .Release.Namespace }}
  releaseName: aws-load-balancer-controller
  targetNamespace: aws-load-balancer-controller
  storageNamespace: aws-load-balancer-controller
  valuesFrom:
    - kind: ConfigMap
      name: {{ $clusterName }}-aws-load-balancer-controller-config
      valuesKey: values
      optional: false
